export enum RouterName {
    HOME = '/',
    LOGIN = '/login',
    REGISTER = '/register',
    ABOUT = '/about',
    RSS_DETAIL = '/rss-detail',
    RSS_BUILDER = '/rss-feed/rss-builder',
    WEBSITE_PREVIEW = '/rss-feed/website-preview',
    MANAGEMENT_HOME = '/management/home',
    RSS = '/management/rss',
    RSS_FEEDS = '/management/rss-feeds',
    BUNDLES = '/management/bundles',
    BUNDLE_FEEDS = '/management/bundle-feeds',
    EXPLORE = '/management/explore',
    SETTINGS = '/settings',
}